### ISSUE TITLE
File session expire when browser sends multiple concurrent requests

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#146] opened 2017-06-12 07:15 UTC
This happens when browser sends to treefrog multiple concurrent requests and each access session stored in file. One of the action threads try to write to file session, and another one reads session from the file at the same time.

In treefrog.log there is ERROR: Failed to load a session from the file store, and then session id is regenerated.

![1](https://user-images.githubusercontent.com/9396016/27022257-700e9dcc-4f4d-11e7-974d-5f10a004af42.png)

In debugger QDataStream::status() returned QDataStream::ReadPastEnd

![2](https://user-images.githubusercontent.com/9396016/27022311-9ea5b404-4f4d-11e7-86f2-51a26939ca59.png)

Please add QWriteLocker in TSessionFileStore::store() just before session in written, and QReadLocker in TSessionFileStore::find() - tried this and worked for me.

Config:
Windows 10 x64
Qt 5.9 +MSVC 2015 32bit
TreeFrog 1.17.0

application.ini:
Session.StoreType=file
Session.AutoIdRegeneration=false
Session.LifeTime=0
Session.CookiePath=/
Session.GcProbability=100
Session.GcMaxLifeTime=1800

**Comment by AmiArt** [comment] 2017-06-20 05:43
Maybe a better solution would be something like this (instead of QReadWriteLock):
https://github.com/qtproject/qt-solutions/tree/master/qtlockedfile

**Comment by treefrogframework** [comment] 2017-06-21 10:04
@AmiArt, Thanks for detailed reporting.
Fixed in 4143fa76c1a675d1c8380417a02d4f5141ff77b7.
Could you test it?

**Comment by AmiArt** [comment] 2017-06-21 10:47
Thank you, but do we really need 2 locks (one for processes and one for threads) ?
Can't we just have one file lock (something like QtLockedFile) which will block both theads and processes ?

In current implementation the **rwLock** is global static variable, so: `QWriteLocker locker(&rwLock); // lock for threads` will block requests for **ALL** sessions (file lock would block only one session).

**Comment by treefrogframework** [comment] 2017-06-21 12:58
2 locks are needed.

> Can't we just have one file lock (something like QtLockedFile) which will block both theads and processes ?
It's compromise.
If you mind the performance really, you can use the session store for Redis.

**Comment by AmiArt** [comment] 2017-06-21 13:04
OK, one more question, why tf_lockfile() doesn't have implementation for Windows ?

**Comment by treefrogframework** [comment] 2017-06-22 02:03
It seems open() function locks against opening by other processes on Qt/Windows, so the function includes locking of the file.
Could you re-test including them?

**Comment by treefrogframework** [comment] 2017-06-22 02:21
App server (tadpole.exe) of TreeFrog is multiprocessing and multithreading. 

application.ini:

    # Number of application server processes to be started.
    MPM.thread.MaxAppServers=4
    
    # Maximum number of action threads allowed to start simultaneously
    # per server process.
    MPM.thread.MaxThreadsPerAppServer=128

**Comment by AmiArt** [comment] 2017-06-24 12:41
Session still expires, but not as often as before.
![1](https://user-images.githubusercontent.com/9396016/27508482-3abfa510-58e6-11e7-852d-15195dc091c8.png)

![2](https://user-images.githubusercontent.com/9396016/27508486-4f5d2c4a-58e6-11e7-9f55-248af91528c1.png)

I think QReadLocker/QWriteLocker should be placed before file is open.

BTW: You mention than 2 locks are needed. I suppose you mean WinAPI LockFile that blocks only processes. But take a look at source code QLockedFile. They don't use LockFile, but named mutexes.

Here is example:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686927(v=vs.85).aspx

**Comment by treefrogframework** [comment] 2017-06-27 03:12
Thanks!
I could not reproduce the bug. I think you are correct.
Fixed in 304560998facbc8434ce92316584d967cbd656aa.
Could you retest it?

Try this setting in application.ini;
```
 SystemLog.Layout="%d %5P (%i) [%t] %m%n"
```

**Comment by AmiArt** [comment] 2017-06-30 05:49
Session still expires. It's because object destruction order is wrong.
Currently objects are destructed in the following order:

~QWriteLocker()    <- releases lock
~QFile()                 <- flushes data to file

If we move QReadLocker/QWriteLocker before QFile like this:

**QWriteLocker locker(&rwLock);  // lock for threads**
QFile file(sessionDirPath() + session.id());

the destruction order would be OK:

~QFile()                 <- flushes data to file
~QWriteLocker()    <- releases lock

**Comment by treefrogframework** [comment] 2017-07-01 02:39
@AmiArt, OK.
Maybe fixed in 9877444e0f9c5bb066cb902e273e23eaae252333.

**Comment by AmiArt** [comment] 2017-07-01 06:23
Finally fixed, thank you very much for help !

**Closed** 2017-07-01 06:24 UTC

**Comment by treefrogframework** [comment] 2017-07-01 07:44
Thank you, too.
